# Generated by Django 2.2.3 on 2021-07-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15, verbose_name='Amount')),
                ('balance', models.CharField(max_length=15, null=True, verbose_name='Amount')),
                ('enable', models.BooleanField(default=False)),
                ('enabled_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Created Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
