# Generated by Django 2.2.3 on 2021-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallet', '0003_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='reference_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Amount'),
        ),
    ]
