# Generated by Django 2.2.3 on 2021-07-13 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniwallet', '0004_deposit_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15, verbose_name='Amount')),
                ('reference_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Amount')),
                ('withdrawal_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner_withdrawal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
