# Generated by Django 2.2.3 on 2021-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallet', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='disabled_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Disabled Time'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='enabled_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Enabled Time'),
        ),
    ]
