# Generated by Django 3.1.4 on 2020-12-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_of_match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Deliveries',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Umpire',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
