# Generated by Django 3.1.4 on 2020-12-06 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_auto_20201206_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Player Name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Team Name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Umpire Name')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Venue')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('season', models.CharField(db_index=True, max_length=500)),
                ('city', models.CharField(db_index=True, max_length=500)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('toss_decision', models.CharField(choices=[('field', 'Field'), ('bat', 'Bat')], default='bat', max_length=50)),
                ('result', models.CharField(choices=[('normal', 'Normal'), ('tie', 'Tie'), ('noresult', 'NoResult')], default='normal', max_length=50)),
                ('dl_applied', models.BooleanField(default=False)),
                ('win_by_runs', models.IntegerField(verbose_name='Win by runs')),
                ('win_by_wickets', models.IntegerField(verbose_name='Win by Wickets')),
                ('player_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player', to='matches.player')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_1', to='matches.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_2', to='matches.team')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='matches.team')),
                ('umpire1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpire1', to='matches.umpire')),
                ('umpire2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpire2', to='matches.umpire')),
                ('umpire3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umpire3', to='matches.umpire')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_venue', to='matches.venue')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='matches.team')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inning', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=50)),
                ('over', models.IntegerField(verbose_name='Over')),
                ('ball', models.IntegerField(verbose_name='Ball')),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField(verbose_name='Wide runs')),
                ('bye_runs', models.IntegerField(verbose_name='Wide runs')),
                ('legbye_runs', models.IntegerField(verbose_name='Wide runs')),
                ('noball_runs', models.IntegerField(verbose_name='Wide runs')),
                ('penalty_runs', models.IntegerField(verbose_name='Wide runs')),
                ('batsman_runs', models.IntegerField(verbose_name='Wide runs')),
                ('extra_runs', models.IntegerField(verbose_name='Wide runs')),
                ('total_runs', models.IntegerField(verbose_name='Wide runs')),
                ('dismissal_kind', models.CharField(db_index=True, max_length=500)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_batsman', to='matches.player')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_bating_team', to='matches.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_bowler', to='matches.player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_bowling_team', to='matches.team')),
                ('fielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_fielder', to='matches.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_match', to='matches.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_non_striker', to='matches.player')),
                ('player_dismissed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_player_dismissed', to='matches.player')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
