# Generated by Django 2.2.3 on 2020-12-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_deliveries_match_player_team_umpire_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dl_applied',
            field=models.IntegerField(verbose_name='Dl Applied'),
        ),
    ]
