# Generated by Django 2.2.3 on 2020-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20201206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='win_by_runs',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_by_wickets',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
