# Generated by Django 2.2.3 on 2020-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20201206_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dl_applied',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
