# Generated by Django 2.2.3 on 2020-12-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20201206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_player', to='matches.Player'),
        ),
    ]
